import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Post from "../components/post";
import PostForm from "../components/PostForm";
import Bio from "../components/Bio";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Bio
          headShot="https://scontent.fluh1-2.fna.fbcdn.net/v/t1.18169-9/13240587_947158508716118_1927243271518457343_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=1gi_w5lVFT8AX8KsETe&_nc_ht=scontent.fluh1-2.fna&oh=df9e903115f46a5f1bce43e2ecfd2ee4&oe=6167818D"
          name="Manav Kaushal"
          tagLine="2021 is an year to level up!"
          role="Frontend Developer @ Spacejoy"
        />
        <ul className={styles.posts}>
          <li>
            <Post content="Hey, I'm a new post!" date="3/2/2021" />
          </li>
          <li>
            <Post content="Hey, I'm a bit older post." date="3/2/2021" />
          </li>
          <li>
            <Post content="Hey, I'm a relatively older post." date="3/2/2021" />
          </li>
          <li>
            <Post content="Hey, I'm a very old post." date="3/2/2021" />
          </li>
        </ul>

        <PostForm />
      </main>
    </div>
  );
}
